server:
  port: 8761

spring:
  application:
    name: eureka-discovery-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
