server:
    port: 8070
spring:
  application:
    name: twitter-goal-analyser

management:
  server:
    port: 8071
    address: 127.0.0.1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: application/json
      min-request-size: 1024