server:
    port: 8090
spring:
  application:
    name: twitter-tweet-collector

management:
  server:
    port: 8091
    address: 127.0.0.1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

twitter4j:
  debug: false
  oauth:
    consumerKey: # Do not paste your information here! Create a application-keys.yml
    consumerSecret: # Do not paste your information here! Create a application-keys.yml
    accessToken: # Do not paste your information here! Create a application-keys.yml
    accessTokenSecret: # Do not paste your information here! Create a application-keys.yml
